// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/pavelz/insta-go/ent/user"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Default: user.DefaultName},
		{Name: "nick", Type: field.TypeString, Default: user.DefaultNick},
		{Name: "nick2", Type: field.TypeString, Default: user.DefaultNick2},
		{Name: "image", Type: field.TypeBytes, Nullable: true, Default: user.DefaultImage},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
