// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/pavelz/insta-go/ent/photo"
	"github.com/pavelz/insta-go/ent/predicate"
)

// PhotoDelete is the builder for deleting a Photo entity.
type PhotoDelete struct {
	config
	predicates []predicate.Photo
}

// Where adds a new predicate to the delete builder.
func (pd *PhotoDelete) Where(ps ...predicate.Photo) *PhotoDelete {
	pd.predicates = append(pd.predicates, ps...)
	return pd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pd *PhotoDelete) Exec(ctx context.Context) (int, error) {
	return pd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (pd *PhotoDelete) ExecX(ctx context.Context) int {
	n, err := pd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pd *PhotoDelete) sqlExec(ctx context.Context) (int, error) {
	var (
		res     sql.Result
		builder = sql.Dialect(pd.driver.Dialect())
	)
	selector := builder.Select().From(sql.Table(photo.Table))
	for _, p := range pd.predicates {
		p(selector)
	}
	query, args := builder.Delete(photo.Table).FromSelect(selector).Query()
	if err := pd.driver.Exec(ctx, query, args, &res); err != nil {
		return 0, err
	}
	affected, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}
	return int(affected), nil
}

// PhotoDeleteOne is the builder for deleting a single Photo entity.
type PhotoDeleteOne struct {
	pd *PhotoDelete
}

// Exec executes the deletion query.
func (pdo *PhotoDeleteOne) Exec(ctx context.Context) error {
	n, err := pdo.pd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{photo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pdo *PhotoDeleteOne) ExecX(ctx context.Context) {
	pdo.pd.ExecX(ctx)
}
