// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/pavelz/insta-go/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	age   *int
	name  *string
	nick  *string
	nick2 *string
	image *[]byte
}

// SetAge sets the age field.
func (uc *UserCreate) SetAge(i int) *UserCreate {
	uc.age = &i
	return uc
}

// SetName sets the name field.
func (uc *UserCreate) SetName(s string) *UserCreate {
	uc.name = &s
	return uc
}

// SetNillableName sets the name field if the given value is not nil.
func (uc *UserCreate) SetNillableName(s *string) *UserCreate {
	if s != nil {
		uc.SetName(*s)
	}
	return uc
}

// SetNick sets the nick field.
func (uc *UserCreate) SetNick(s string) *UserCreate {
	uc.nick = &s
	return uc
}

// SetNillableNick sets the nick field if the given value is not nil.
func (uc *UserCreate) SetNillableNick(s *string) *UserCreate {
	if s != nil {
		uc.SetNick(*s)
	}
	return uc
}

// SetNick2 sets the nick2 field.
func (uc *UserCreate) SetNick2(s string) *UserCreate {
	uc.nick2 = &s
	return uc
}

// SetNillableNick2 sets the nick2 field if the given value is not nil.
func (uc *UserCreate) SetNillableNick2(s *string) *UserCreate {
	if s != nil {
		uc.SetNick2(*s)
	}
	return uc
}

// SetImage sets the image field.
func (uc *UserCreate) SetImage(b []byte) *UserCreate {
	uc.image = &b
	return uc
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	if uc.age == nil {
		return nil, errors.New("ent: missing required field \"age\"")
	}
	if err := user.AgeValidator(*uc.age); err != nil {
		return nil, fmt.Errorf("ent: validator failed for field \"age\": %v", err)
	}
	if uc.name == nil {
		v := user.DefaultName
		uc.name = &v
	}
	if uc.nick == nil {
		v := user.DefaultNick
		uc.nick = &v
	}
	if uc.nick2 == nil {
		v := user.DefaultNick2
		uc.nick2 = &v
	}
	if uc.image == nil {
		v := user.DefaultImage
		uc.image = &v
	}
	return uc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	var (
		builder = sql.Dialect(uc.driver.Dialect())
		u       = &User{config: uc.config}
	)
	tx, err := uc.driver.Tx(ctx)
	if err != nil {
		return nil, err
	}
	insert := builder.Insert(user.Table).Default()
	if value := uc.age; value != nil {
		insert.Set(user.FieldAge, *value)
		u.Age = *value
	}
	if value := uc.name; value != nil {
		insert.Set(user.FieldName, *value)
		u.Name = *value
	}
	if value := uc.nick; value != nil {
		insert.Set(user.FieldNick, *value)
		u.Nick = *value
	}
	if value := uc.nick2; value != nil {
		insert.Set(user.FieldNick2, *value)
		u.Nick2 = *value
	}
	if value := uc.image; value != nil {
		insert.Set(user.FieldImage, *value)
		u.Image = *value
	}
	id, err := insertLastID(ctx, tx, insert.Returning(user.FieldID))
	if err != nil {
		return nil, rollback(tx, err)
	}
	u.ID = int(id)
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return u, nil
}
