// Code generated by entc, DO NOT EDIT.

package photo

import (
	"github.com/pavelz/insta-go/ent/schema"
)

const (
	// Label holds the string label denoting the photo type in the database.
	Label = "photo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLat holds the string denoting the lat vertex property in the database.
	FieldLat = "lat"
	// FieldLng holds the string denoting the lng vertex property in the database.
	FieldLng = "lng"
	// FieldImage holds the string denoting the image vertex property in the database.
	FieldImage = "image"
	// FieldFielname holds the string denoting the fielname vertex property in the database.
	FieldFielname = "fielname"

	// Table holds the table name of the photo in the database.
	Table = "photos"
)

// Columns holds all SQL columns are photo fields.
var Columns = []string{
	FieldID,
	FieldLat,
	FieldLng,
	FieldImage,
	FieldFielname,
}

var (
	fields = schema.Photo{}.Fields()

	// descLat is the schema descriptor for lat field.
	descLat = fields[0].Descriptor()
	// DefaultLat holds the default value on creation for the lat field.
	DefaultLat = descLat.Default.(float64)

	// descLng is the schema descriptor for lng field.
	descLng = fields[1].Descriptor()
	// DefaultLng holds the default value on creation for the lng field.
	DefaultLng = descLng.Default.(float64)
)
