// Code generated by entc, DO NOT EDIT.

package user

import (
	"github.com/pavelz/insta-go/ent/schema"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age vertex property in the database.
	FieldAge = "age"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldNick holds the string denoting the nick vertex property in the database.
	FieldNick = "nick"
	// FieldNick2 holds the string denoting the nick2 vertex property in the database.
	FieldNick2 = "nick2"
	// FieldImage holds the string denoting the image vertex property in the database.
	FieldImage = "image"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns are user fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldName,
	FieldNick,
	FieldNick2,
	FieldImage,
}

var (
	fields = schema.User{}.Fields()

	// descAge is the schema descriptor for age field.
	descAge = fields[0].Descriptor()
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator = descAge.Validators[0].(func(int) error)

	// descName is the schema descriptor for name field.
	descName = fields[1].Descriptor()
	// DefaultName holds the default value on creation for the name field.
	DefaultName = descName.Default.(string)

	// descNick is the schema descriptor for nick field.
	descNick = fields[2].Descriptor()
	// DefaultNick holds the default value on creation for the nick field.
	DefaultNick = descNick.Default.(string)

	// descNick2 is the schema descriptor for nick2 field.
	descNick2 = fields[3].Descriptor()
	// DefaultNick2 holds the default value on creation for the nick2 field.
	DefaultNick2 = descNick2.Default.(string)

	// descImage is the schema descriptor for image field.
	descImage = fields[4].Descriptor()
	// DefaultImage holds the default value on creation for the image field.
	DefaultImage = descImage.Default.([]byte)
)
