// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Photo is the predicate function for photo builders.
type Photo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
